# Add brew binaries to the path
eval $(/opt/homebrew/bin/brew shellenv)

source $DOTFILES/common/shrc
source $DOTFILES/macos/functions.sh
source $DOTFILES/macos/aliases.sh
source $DOTFILES/macos/autocompletion.sh
source $DOTFILES/macos/starship.sh
source $DOTFILES/macos/exports.sh

# Solución al problema de que salga fondo blanco al pegar texto en consola
# https://news.ycombinator.com/item?id=26757438
zle_highlight+=(paste:none)

ssh-add $HOME/.ssh/id_rsa 2> /dev/null

eval "$(zoxide init zsh)"

# Try to activate venv if proceed
venv_autoactivate
