alias clean_pyc="find . -name *.pyc -exec rm {} \;"
alias serve="python -m http.server"
alias tree="tree -C"
alias ll='lsd -F -l --date relative'
alias lla='lsd -F -la --date relative'
alias bat='bat -p'
alias g='rg'
alias f='fd'
alias c='cd ~/code'
alias v='source .venv/bin/activate'
