# https://docs.astral.sh/ruff/settings/
line-length = 100

[lint]
extend-select = ["Q", "ARG001"]

[lint.flake8-quotes]
inline-quotes = "single"

[format]
quote-style = "single"

[lint.flake8-unused-arguments]
ignore-variadic-names = true
