# https://starship.rs/config/
# Colores → https://i.sstatic.net/KTSQa.png
# Iconos → https://www.nerdfonts.com/cheat-sheet
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$hostname\
$directory\
${custom.uv}\
${custom.virtualenv}\
$git_branch\
$git_status\
\n[╰─](dimmed)\
$character"""

add_newline = false

[os]
disabled = false
format = '[$symbol](dimmed) '

[os.symbols]
Macos = ''
Debian = ''

[hostname]
format = '[$hostname](green italic) '

[directory]
truncate_to_repo = false
truncation_length = 8
format = '[](fg:#3B76F0)[ 󰝰 $path ](bg:#3B76F0 fg:#c8ebf7)[](fg:#3B76F0)'

[custom.uv]
command = 'uv run python --version | sed "s/Python //"'
when = '[[ -n $UV_ENV ]]'
format = '[](#DE60E9)[ uv](bg:#DE60E9 fg:#480D4D italic)[  $output ](bg:#DE60E9 fg:#480D4D)[](#DE60E9)'

[custom.virtualenv]
command = "python --version | perl -ne 'print $1 if /[Pp]ython *(.*)/'"
when = "[[ -n $VIRTUAL_ENV ]]"
format = '[](#e8cc17)[ venv](bg:#e8cc17 fg:#423a07 italic)[ 󰌪 $output ](bg:#e8cc17 fg:#423a07)[](#e8cc17)'

[git_branch]
format = '[](#0ee8d9)[  $branch(:$remote_branch) ](bg:#0ee8d9 fg:#022926)[ ](#0ee8d9)'

[git_status]
style = 'bold #0ee8d9'
