# https://starship.rs/config/
# Colores → https://i.sstatic.net/KTSQa.png
# Iconos → https://www.nerdfonts.com/cheat-sheet
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$hostname\
$directory\
${custom.uv}\
${custom.virtualenv}\
$git_branch\
$git_status\
\n[╰─](dimmed)\
$character"""

add_newline = false

[os]
disabled = false
format = '[$symbol](dimmed) '

[os.symbols]
Macos = ''
Debian = ''

[hostname]
format = '[](fg:#999999)[󰬀󰬀󰫵 $hostname](dimmed bg:#999999 fg:black)[](fg:#999999) '

[directory]
truncate_to_repo = false
truncation_length = 8
truncation_symbol = '…/'
format = '[](fg:#394260)[󰝰 $path ](bg:#394260 fg:#769ff0)[󰋑 ](bg:#394260 fg:#141A3B)[](fg:#394260)'

[custom.uv]
command = 'uv run python --version | sed "s/Python //"'
when = '[[ -n $UV_ENV ]]'
format = '[](#2B0117)[ uv](bg:#2B0117 fg:#de60e9 italic)[  $output ](bg:#2B0117 fg:#de60e9)[](#2B0117)'

[custom.virtualenv]
command = "python --version | perl -ne 'print $1 if /[Pp]ython *(.*)/'"
when = "[[ -n $VIRTUAL_ENV ]]"
format = '[](#4F4E00)[ venv](bg:#4F4E00 fg:#F7E316 italic)[ 󰌪 $output ](bg:#4F4E00 fg:#F7E316)[](#4F4E00)'

[git_branch]
format = '[](#022B24)[  $branch(:$remote_branch) ](bg:#022B24 fg:#58F405)[](#022B24)'

[git_status]
format = '[](#311B00)[  $all_status$ahead_behind](bg:#311B00 fg:#F66E01)[](#311B00)'

[character]
success_symbol = '[󰅂](bold #29F407)'
error_symbol = '[󰅂](bold #F55448)'
