# https://starship.rs/config/
# Colores → https://i.sstatic.net/KTSQa.png
# Iconos → https://www.nerdfonts.com/cheat-sheet
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$hostname\
$directory\
${custom.uv}\
${custom.virtualenv}\
${custom.R}\
$git_branch\
${custom.git}\
${custom.github}\
\n[╰─](dimmed)\
$character"""

add_newline = false

[os]
disabled = false
format = '[$symbol](dimmed) '

[os.symbols]
Macos = ''
Debian = ''

[hostname]
format = '[](fg:#999999)[󰬀󰬀󰫵 $hostname](dimmed bg:#999999 fg:black)[](fg:#999999) '

[directory]
truncate_to_repo = false
truncation_length = 8
truncation_symbol = '…/'
format = '[](fg:#394260)[󰝰 $path ](bg:#394260 fg:#769ff0)[󰋑 ](bg:#394260 fg:#141A3B)[](fg:#394260)'

[custom.files]
command = "ls -1A | wc -l"
format = '[](#432D1D)[ 󰪶 $output ](bg:#432D1D fg:#CF927C)[](#432D1D)'
when = ''

[custom.uv]
command = 'uv run python --version | sed "s/Python //"'
when = '[[ -n $UV_ENV ]]'
format = '[](#2B0117)[ uv](bg:#2B0117 fg:#de60e9 italic)[  $output ](bg:#2B0117 fg:#de60e9)[](#2B0117)'

[custom.virtualenv]
command = "python --version | perl -ne 'print $1 if /[Pp]ython *(.*)/'"
when = "[[ -n $VIRTUAL_ENV ]]"
format = '[](#4F4E00)[ venv](bg:#4F4E00 fg:#F7E316 italic)[ 󰌪 $output ](bg:#4F4E00 fg:#F7E316)[](#4F4E00)'

[custom.R]
command = "R --version | perl -ne 'print $1 if /R version *(\\d+\\.\\d+\\.\\d+)/'"
format = '[](#3C3420)[ 󰫿 󰋙 $output ](bg:#3C3420 fg:#F1AF4C)[](#3C3420)'
detect_extensions = ['R', 'Rmd']

[git_branch]
format = '[](#022B24)[  $branch(:$remote_branch) ](bg:#022B24 fg:#58F405)[](#022B24)'

[custom.git]
command = "git status --porcelain | perl -ne 'BEGIN {%MAP=(\"A\"=>\"A\", \"M\"=>\"M\", \"D\"=>\"D\", \"??\"=>\"U\")} print \"$MAP{$1}\n\" if /^\\s*([\\S]+)/' | sort | uniq | tr -d '\n'"
when = '[ -n "$(git status --porcelain)" ]'
format = '[](#311B00)[ 󰜘 $output ](bg:#311B00 fg:#F66E01)[](#311B00)'

[custom.github]
command = "git status -uno | perl -0ne 'BEGIN {%MAP=(\"ahead\"=>\"󰕒\", \"behind\"=>\"󰇚\")} print $MAP{$1} if /.*(ahead|pepe).*/'"
when = "git status -uno | grep -E 'behind|ahead'"
format = '[](#252E38)[ 󰊤 $output ](bg:#252E38 fg:#A4A4A4)[](#252E38)'

[character]
success_symbol = '[󰅂](bold #29F407)'
error_symbol = '[󰅂](bold #F55448)'
