source $DOTFILES/common/shrc
source $DOTFILES/linux/functions.sh
source $DOTFILES/linux/aliases.sh
source $DOTFILES/linux/prompt.sh
source $DOTFILES/linux/pyenv-init.sh
source $DOTFILES/linux/autocompletion.sh

bind 'set enable-bracketed-paste off'
export EDITOR=/usr/bin/vim
# La visualización del prompt para virtualenv se hace en prompt.sh
VIRTUAL_ENV_DISABLE_PROMPT=1
eval "$(zoxide init --cmd cd bash)"
