name: CI
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy project
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote deploy commands
        uses: appleboy/ssh-action@master
        with:
          host: sdelquin.me
          username: ${{ secrets.PRODUCTION_SSH_USERNAME }}
          key: ${{ secrets.PRODUCTION_SSH_KEY }}
          script: cd ~/.dotfiles && git pull && vim +'PlugInstall --sync' +qa
